# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf98acc92cea87fd13b4fc00b06aafd6e6bafe1e6fcfa345cec98daeeab9c9176724d739d6164f263b3e565b288a8b390c1c77a102e20c93d5e50150f6dfd47

test:
  secret_key_base: a85bb30cce6b411344585de7b94547af30306b0907911aa9246c8fd33ae96076ba6bc260b9a51154979526178a0430bf14214fec2c7f676c24eeb48848977171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
